from collections.abc import Iterable, Iterator, MutableSequence
from typing import Any, Literal, Optional, SupportsIndex, TypeVar, overload

from .abstract import MatrixLike
from .shapes import Shape, ShapeView
from .typeshed import (SupportsAbs, SupportsAdd, SupportsAnd,
                       SupportsConjugate, SupportsDivMod, SupportsDotProduct,
                       SupportsFloorDiv, SupportsInvert, SupportsLShift,
                       SupportsMod, SupportsMonomorphicAdd, SupportsMul,
                       SupportsNeg, SupportsOr, SupportsPos, SupportsPow,
                       SupportsRAdd, SupportsRAnd, SupportsRDivMod,
                       SupportsRDotProduct, SupportsRFloorDiv, SupportsRLShift,
                       SupportsRMod, SupportsRMul, SupportsROr, SupportsRPow,
                       SupportsRRShift, SupportsRShift, SupportsRSub,
                       SupportsRTrueDiv, SupportsRXor, SupportsSub,
                       SupportsTrueDiv, SupportsXor)
from .utilities import Rule

T = TypeVar("T")
T_co = TypeVar("T_co", covariant=True)

T1 = TypeVar("T1")
T2 = TypeVar("T2")

M_co = TypeVar("M_co", covariant=True, bound=int)
N_co = TypeVar("N_co", covariant=True, bound=int)
P_co = TypeVar("P_co", covariant=True, bound=int)

SupportsMonomorphicAddT = TypeVar("SupportsMonomorphicAddT", bound=SupportsMonomorphicAdd)


FrozenMatrixT = TypeVar("FrozenMatrixT", bound=FrozenMatrix)

class FrozenMatrix(MatrixLike[T_co, M_co, N_co]):

    __slots__: tuple[Literal["_array"], Literal["_shape"]]

    def __init__(self, data: Optional[Iterable[T_co]], nrows: Optional[M_co] = None, ncols: Optional[N_co] = None) -> None: ...
    def __repr__(self) -> str: ...
    @overload
    def __getitem__(self, key: SupportsIndex) -> T_co: ...
    @overload
    def __getitem__(self, key: slice) -> FrozenMatrix[T_co, Literal[1], int]: ...
    @overload
    def __getitem__(self, key: tuple[SupportsIndex, SupportsIndex]) -> T_co: ...
    @overload
    def __getitem__(self, key: tuple[SupportsIndex, slice]) -> FrozenMatrix[T_co, Literal[1], int]: ...
    @overload
    def __getitem__(self, key: tuple[slice, SupportsIndex]) -> FrozenMatrix[T_co, int, Literal[1]]: ...
    @overload
    def __getitem__(self, key: tuple[slice, slice]) -> FrozenMatrix[T_co, int, int]: ...
    def __iter__(self) -> Iterator[T_co]: ...
    def __reversed__(self) -> Iterator[T_co]: ...
    def __contains__(self, value: Any) -> bool: ...
    @overload
    def __add__(self: MatrixLike[SupportsAdd[T1, T2], M_co, N_co], other: MatrixLike[T1, M_co, N_co]) -> FrozenMatrix[T2, M_co, N_co]: ...
    @overload
    def __add__(self: MatrixLike[T1, M_co, N_co], other: MatrixLike[SupportsRAdd[T1, T2], M_co, N_co]) -> FrozenMatrix[T2, M_co, N_co]: ...
    @overload
    def __sub__(self: MatrixLike[SupportsSub[T1, T2], M_co, N_co], other: MatrixLike[T1, M_co, N_co]) -> FrozenMatrix[T2, M_co, N_co]: ...
    @overload
    def __sub__(self: MatrixLike[T1, M_co, N_co], other: MatrixLike[SupportsRSub[T1, T2], M_co, N_co]) -> FrozenMatrix[T2, M_co, N_co]: ...
    @overload
    def __mul__(self: MatrixLike[SupportsMul[T1, T2], M_co, N_co], other: MatrixLike[T1, M_co, N_co]) -> FrozenMatrix[T2, M_co, N_co]: ...
    @overload
    def __mul__(self: MatrixLike[T1, M_co, N_co], other: MatrixLike[SupportsRMul[T1, T2], M_co, N_co]) -> FrozenMatrix[T2, M_co, N_co]: ...
    @overload
    def __truediv__(self: MatrixLike[SupportsTrueDiv[T1, T2], M_co, N_co], other: MatrixLike[T1, M_co, N_co]) -> FrozenMatrix[T2, M_co, N_co]: ...
    @overload
    def __truediv__(self: MatrixLike[T1, M_co, N_co], other: MatrixLike[SupportsRTrueDiv[T1, T2], M_co, N_co]) -> FrozenMatrix[T2, M_co, N_co]: ...
    @overload
    def __floordiv__(self: MatrixLike[SupportsFloorDiv[T1, T2], M_co, N_co], other: MatrixLike[T1, M_co, N_co]) -> FrozenMatrix[T2, M_co, N_co]: ...
    @overload
    def __floordiv__(self: MatrixLike[T1, M_co, N_co], other: MatrixLike[SupportsRFloorDiv[T1, T2], M_co, N_co]) -> FrozenMatrix[T2, M_co, N_co]: ...
    @overload
    def __mod__(self: MatrixLike[SupportsMod[T1, T2], M_co, N_co], other: MatrixLike[T1, M_co, N_co]) -> FrozenMatrix[T2, M_co, N_co]: ...
    @overload
    def __mod__(self: MatrixLike[T1, M_co, N_co], other: MatrixLike[SupportsRMod[T1, T2], M_co, N_co]) -> FrozenMatrix[T2, M_co, N_co]: ...
    @overload
    def __divmod__(self: MatrixLike[SupportsDivMod[T1, T2], M_co, N_co], other: MatrixLike[T1, M_co, N_co]) -> FrozenMatrix[T2, M_co, N_co]: ...
    @overload
    def __divmod__(self: MatrixLike[T1, M_co, N_co], other: MatrixLike[SupportsRDivMod[T1, T2], M_co, N_co]) -> FrozenMatrix[T2, M_co, N_co]: ...
    @overload
    def __pow__(self: MatrixLike[SupportsPow[T1, T2], M_co, N_co], other: MatrixLike[T1, M_co, N_co]) -> FrozenMatrix[T2, M_co, N_co]: ...
    @overload
    def __pow__(self: MatrixLike[T1, M_co, N_co], other: MatrixLike[SupportsRPow[T1, T2], M_co, N_co]) -> FrozenMatrix[T2, M_co, N_co]: ...
    @overload
    def __lshift__(self: MatrixLike[SupportsLShift[T1, T2], M_co, N_co], other: MatrixLike[T1, M_co, N_co]) -> FrozenMatrix[T2, M_co, N_co]: ...
    @overload
    def __lshift__(self: MatrixLike[T1, M_co, N_co], other: MatrixLike[SupportsRLShift[T1, T2], M_co, N_co]) -> FrozenMatrix[T2, M_co, N_co]: ...
    @overload
    def __rshift__(self: MatrixLike[SupportsRShift[T1, T2], M_co, N_co], other: MatrixLike[T1, M_co, N_co]) -> FrozenMatrix[T2, M_co, N_co]: ...
    @overload
    def __rshift__(self: MatrixLike[T1, M_co, N_co], other: MatrixLike[SupportsRRShift[T1, T2], M_co, N_co]) -> FrozenMatrix[T2, M_co, N_co]: ...
    @overload
    def __and__(self: MatrixLike[SupportsAnd[T1, T2], M_co, N_co], other: MatrixLike[T1, M_co, N_co]) -> FrozenMatrix[T2, M_co, N_co]: ...
    @overload
    def __and__(self: MatrixLike[T1, M_co, N_co], other: MatrixLike[SupportsRAnd[T1, T2], M_co, N_co]) -> FrozenMatrix[T2, M_co, N_co]: ...
    @overload
    def __xor__(self: MatrixLike[SupportsXor[T1, T2], M_co, N_co], other: MatrixLike[T1, M_co, N_co]) -> FrozenMatrix[T2, M_co, N_co]: ...
    @overload
    def __xor__(self: MatrixLike[T1, M_co, N_co], other: MatrixLike[SupportsRXor[T1, T2], M_co, N_co]) -> FrozenMatrix[T2, M_co, N_co]: ...
    @overload
    def __or__(self: MatrixLike[SupportsOr[T1, T2], M_co, N_co], other: MatrixLike[T1, M_co, N_co]) -> FrozenMatrix[T2, M_co, N_co]: ...
    @overload
    def __or__(self: MatrixLike[T1, M_co, N_co], other: MatrixLike[SupportsROr[T1, T2], M_co, N_co]) -> FrozenMatrix[T2, M_co, N_co]: ...
    def __neg__(self: MatrixLike[SupportsNeg[T], M_co, N_co]) -> FrozenMatrix[T, M_co, N_co]: ...
    def __pos__(self: MatrixLike[SupportsPos[T], M_co, N_co]) -> FrozenMatrix[T, M_co, N_co]: ...
    def __abs__(self: MatrixLike[SupportsAbs[T], M_co, N_co]) -> FrozenMatrix[T, M_co, N_co]: ...
    def __invert__(self: MatrixLike[SupportsInvert[T], M_co, N_co]) -> FrozenMatrix[T, M_co, N_co]: ...
    @overload
    def __matmul__(self: MatrixLike[SupportsDotProduct[T, SupportsMonomorphicAddT], M_co, N_co], other: MatrixLike[T, N_co, P_co]) -> FrozenMatrix[SupportsMonomorphicAddT, M_co, P_co]: ...
    @overload
    def __matmul__(self: MatrixLike[T, M_co, N_co], other: MatrixLike[SupportsRDotProduct[T, SupportsMonomorphicAddT], N_co, P_co]) -> FrozenMatrix[SupportsMonomorphicAddT, M_co, P_co]: ...

    @classmethod
    def wrap(cls: type[FrozenMatrixT], array: MutableSequence[T_co], shape: Shape[M_co, N_co]) -> FrozenMatrixT: ...
    @classmethod
    def infer(cls: type[FrozenMatrixT], rows: Iterable[Iterable[T_co]]) -> FrozenMatrixT: ...

    @property
    def shape(self) -> ShapeView[M_co, N_co]: ...
    @property
    def nrows(self) -> M_co: ...
    @property
    def ncols(self) -> N_co: ...
    @property
    def size(self) -> int: ...

    def eq(self, other: MatrixLike[Any, M_co, N_co]) -> FrozenMatrix[bool, M_co, N_co]: ...
    def ne(self, other: MatrixLike[Any, M_co, N_co]) -> FrozenMatrix[bool, M_co, N_co]: ...
    def lt(self, other: MatrixLike[T_co, M_co, N_co]) -> FrozenMatrix[bool, M_co, N_co]: ...
    def le(self, other: MatrixLike[T_co, M_co, N_co]) -> FrozenMatrix[bool, M_co, N_co]: ...
    def gt(self, other: MatrixLike[T_co, M_co, N_co]) -> FrozenMatrix[bool, M_co, N_co]: ...
    def ge(self, other: MatrixLike[T_co, M_co, N_co]) -> FrozenMatrix[bool, M_co, N_co]: ...
    def conjugate(self: MatrixLike[SupportsConjugate[T], M_co, N_co]) -> FrozenMatrix[T, M_co, N_co]: ...
    @overload
    def slices(self, *, by: Literal[Rule.ROW]) -> Iterator[FrozenMatrix[T_co, Literal[1], N_co]]: ...
    @overload
    def slices(self, *, by: Literal[Rule.COL]) -> Iterator[FrozenMatrix[T_co, M_co, Literal[1]]]: ...
    @overload
    def slices(self, *, by: Rule) -> Iterator[FrozenMatrix[T_co, int, int]]: ...
    @overload
    def slices(self) -> Iterator[FrozenMatrix[T_co, Literal[1], N_co]]: ...
