from collections.abc import Iterator
from typing import (Any, Literal, Optional, SupportsIndex, TypeVar, final,
                    overload)

from .abstract import ShapeLike

__all__ = ["ShapeView"]

NRowsT_co = TypeVar("NRowsT_co", covariant=True, bound=int)
NColsT_co = TypeVar("NColsT_co", covariant=True, bound=int)


@final
class ShapeView(ShapeLike[NRowsT_co, NColsT_co]):

    __slots__: tuple[Literal["_target"]]

    def __init__(self, target: ShapeLike[NRowsT_co, NColsT_co]) -> None: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    @overload
    def __getitem__(self, key: Literal[0]) -> NRowsT_co: ...
    @overload
    def __getitem__(self, key: Literal[1]) -> NColsT_co: ...
    @overload
    def __getitem__(self, key: SupportsIndex) -> NRowsT_co | NColsT_co: ...
    def __iter__(self) -> Iterator[NRowsT_co | NColsT_co]: ...
    def __reversed__(self) -> Iterator[NRowsT_co | NColsT_co]: ...
    def __contains__(self, value: Any) -> bool: ...
    def __deepcopy__(self, memo: Optional[dict[int, Any]] = None) -> ShapeView[NRowsT_co, NColsT_co]: ...
    def __copy__(self) -> ShapeView[NRowsT_co, NColsT_co]: ...
