name: Sphinx build

on:
  push:
    branches:
      - main
  pull_request:

jobs:

  docs:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'

    - name: Upgrade pip
      run: python3 -m pip install --upgrade pip

    - name: Install dependencies
      run: python3 -m pip install -r ./docs/requirements.txt

    - name: Build HTML
      run: |
        cd docs
        make html

    # - name: Upload artifacts
    #   uses: actions/upload-artifact@v3
    #   with:
    #     name: html-docs
    #     path: docs/build/html/

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/build/html
